---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  tasks:
    # delete directory if condition is true
  - name: Removing old JAVA SDK packages
    file:
      state: absent
      path: '{{ item  }}'
    with_items: 
      - /u01/java/jdk1.8.0_150
      - /u01/java/jdk1.8.0_194
      - /u01/java/jdk1.8.0_195
  - name: Check if OracleWeblogicNodeManager services are deployed
    command: systemctl is-enabled --quiet "{{ item }}"
    register: weblogic_services_enabled
    ignore_errors: true
    with_items:
      - OracleWeblogicNmService_11c
      - OracleWeblogicNmService_12c
  - debug:
       var: weblogic_services_enabled
  - name: Check that services are running
    command: systemctl is-active --quiet "{{ item.item }}"
    with_items: "{{ weblogic_services_enabled.results }}"
    when: item.rc == 0
  - name: Stop and disable Oracle Weblogic Nodemanager services
    service: name={{ item.item }} state=stopped enabled=no
    with_items: "{{ weblogic_services_enabled.results }}"
    when: item.rc == 0

